### ISSUE TITLE
Resize fails in quarto if a table has a note

### ISSUE THREAD

**Issue by MarcoPortmann** [vincentarelbundock/tinytable#206]
`theme_tt(theme = "resize"...` will not work in quarto if the table contains a note:

````markdown
---
format: 
  pdf

---

```{r message=TRUE, include=FALSE}
library(tidyverse)
library(tinytable)
```

```{r}
#| echo: FALSE
#| label: tbl-test
#| tbl-cap: "My table"

tibble(X = 1) %>% 
  tt(note = "abc") %>% 
  theme_tt(theme = "resize", width = 0.9)
```
````
This will lead to the following error:

```r
Quitting from lines 13-20 [tbl-test] (testdoc.qmd)
Error:
! The `regex` supplied `lines_drop()` did not match a unique line.
Backtrace:
  1. global .main()
  2. execute(...)
  3. rmarkdown::render(...)
  4. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  5. knitr:::process_file(text, output)
     ...
 26. tinytable::knit_print.tinytable(x, ...)
 27. tinytable:::build_tt(x, output = output)
 29. tinytable:::finalize(x)
 30. tinytable (local) fn(x)
 31. tinytable:::lines_insert(tab, regex = reg, new = new, position = "before")
                                                                                                            
Execution halted
```

**Comment by vincentarelbundock** [comment]
Thanks for the report. Should be fixed on Github:

``` r
library(tinytable)
data.frame(X = 1) |>
  tt(note = "abc") |>
  theme_tt(theme = "resize", width = 0.9) |>
  print("latex")
```

    \begin{table}
    \centering
    \resizebox{\ifdim\width>\linewidth 0.9\linewidth\else\width\fi}{!}{
    \begin{talltblr}[         %% tabularray outer open
    entry=none,label=none,
    note{}={abc},
    ]                     %% tabularray outer close
    {                     %% tabularray inner open
    colspec={Q[]},
    }                     %% tabularray inner close
    \toprule
    X \\ \midrule %% TinyTableHeader
    1 \\
    \bottomrule
    \end{talltblr}
    }
    \end{table}

**Comment by danieltomasz** [comment]
This is still happening with tinytable 0.5 and quartoi 1.6.32 (both Rstudio and vscode)

````

### Tables

Here are a couple of example tables
```{r}
#| label: tbl-example
#| tbl-cap: Table created with `tinytable::tt()`
#| echo: true
library(tinytable)
print(packageVersion("tinytable"))
set.seed(1)
data <- data.frame(x = rnorm(30), y = rnorm(30))
tinytable::tt(
    head(data, 2),
    digits = 2,
    notes = "Note. This is a footnote."
)
````

**Comment by vincentarelbundock** [comment]
This appears to work on version 0.5.0.5 from Github:

````
---
format: pdf
---

```{r}
#| label: tbl-example
#| tbl-cap: Table created with `tinytable::tt()`
#| echo: true
print(packageVersion("tinytable"))
library(tinytable)
set.seed(1)

data <- data.frame(x = rnorm(30), y = rnorm(30))

tt(head(data, 2), digits = 2, notes = "blah blah") |> 
    theme_tt('resize', direction = "up")
```
````

**Comment by danieltomasz** [comment]
@vincentarelbundock yes, I can confirm there is no issues, I had earlier installed cran version, thanks!
